### PR TITLE
JDP210201-24 created

### PR DESCRIPTION
**Pull request by pawelski85**
OrderMapper class created, OrderController updated

### CODE REVIEW

**Review by Ktubbo — CHANGES_REQUESTED** [review]
This mapper does not work properly.

**Comment by pawelski85** [comment]
> This mapper does not work properly.

what error do you have?

**Comment by Ktubbo** [comment]
> 
> 
> > This mapper does not work properly.
> 
> what error do you have?

This mapper in every method return empty objects. It means that it is mapping nothing. Look how other mappers looks like.

**Comment by pawelski85** [comment]
> > > This mapper does not work properly.
> > 
> > 
> > what error do you have?
> 
> This mapper in every method return empty objects. It means that it is mapping nothing. Look how other mappers looks like.

Ok, thanks, its modified now.

**Review by lukkra1989 — APPROVED** [review]

**Review by Ktubbo — APPROVED** [review]

**Pull request merged**
